#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=10

NAME=tswatchdog
BIN=/usr/bin/ts-watchdog

start_service() {
	local enabled

	. /lib/functions.sh
	config_load "$NAME"
	config_get_bool enabled config enabled 1

	[ "$enabled" = "1" ] || return 0

	procd_open_instance
	procd_set_param command "$BIN"
	procd_set_param respawn 60 5 5
	procd_set_param stdout 0
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "$NAME"
}
